name: CI Validation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Leverage Cache
        uses: Swatinem/rust-cache@v1
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build for Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Deploy
        uses: actions-rs/cargo@v1
        with:
          command: publish